//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockClient.DataRetrieval {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataRetrieval.DataRetrievalServiceSoap")]
    public interface DataRetrievalServiceSoap {
        
        // CODEGEN: Generating message contract since element name ThreeLetterISO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStock", ReplyAction="*")]
        StockClient.DataRetrieval.GetStockResponse GetStock(StockClient.DataRetrieval.GetStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStock", ReplyAction="*")]
        System.Threading.Tasks.Task<StockClient.DataRetrieval.GetStockResponse> GetStockAsync(StockClient.DataRetrieval.GetStockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStock", Namespace="http://tempuri.org/", Order=0)]
        public StockClient.DataRetrieval.GetStockRequestBody Body;
        
        public GetStockRequest() {
        }
        
        public GetStockRequest(StockClient.DataRetrieval.GetStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ThreeLetterISO;
        
        public GetStockRequestBody() {
        }
        
        public GetStockRequestBody(string ThreeLetterISO) {
            this.ThreeLetterISO = ThreeLetterISO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public StockClient.DataRetrieval.GetStockResponseBody Body;
        
        public GetStockResponse() {
        }
        
        public GetStockResponse(StockClient.DataRetrieval.GetStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStockResult;
        
        public GetStockResponseBody() {
        }
        
        public GetStockResponseBody(string GetStockResult) {
            this.GetStockResult = GetStockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataRetrievalServiceSoapChannel : StockClient.DataRetrieval.DataRetrievalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataRetrievalServiceSoapClient : System.ServiceModel.ClientBase<StockClient.DataRetrieval.DataRetrievalServiceSoap>, StockClient.DataRetrieval.DataRetrievalServiceSoap {
        
        public DataRetrievalServiceSoapClient() {
        }
        
        public DataRetrievalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataRetrievalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRetrievalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRetrievalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockClient.DataRetrieval.GetStockResponse StockClient.DataRetrieval.DataRetrievalServiceSoap.GetStock(StockClient.DataRetrieval.GetStockRequest request) {
            return base.Channel.GetStock(request);
        }
        
        public string GetStock(string ThreeLetterISO) {
            StockClient.DataRetrieval.GetStockRequest inValue = new StockClient.DataRetrieval.GetStockRequest();
            inValue.Body = new StockClient.DataRetrieval.GetStockRequestBody();
            inValue.Body.ThreeLetterISO = ThreeLetterISO;
            StockClient.DataRetrieval.GetStockResponse retVal = ((StockClient.DataRetrieval.DataRetrievalServiceSoap)(this)).GetStock(inValue);
            return retVal.Body.GetStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockClient.DataRetrieval.GetStockResponse> StockClient.DataRetrieval.DataRetrievalServiceSoap.GetStockAsync(StockClient.DataRetrieval.GetStockRequest request) {
            return base.Channel.GetStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockClient.DataRetrieval.GetStockResponse> GetStockAsync(string ThreeLetterISO) {
            StockClient.DataRetrieval.GetStockRequest inValue = new StockClient.DataRetrieval.GetStockRequest();
            inValue.Body = new StockClient.DataRetrieval.GetStockRequestBody();
            inValue.Body.ThreeLetterISO = ThreeLetterISO;
            return ((StockClient.DataRetrieval.DataRetrievalServiceSoap)(this)).GetStockAsync(inValue);
        }
    }
}
